name: laravel-app
recipe: laravel
config:
  php: '7.4'
  via: apache
  webroot: .
  database: mysql:5.7
  cache: none
  xdebug: true
  ssl: true
proxy:
  appserver:
    - web.lv.lndo.site
  database:
    - db.lv.lndo.site
  mailhog:
    - mail.lv.lndo.site
  pma:
    - pma.lv.lndo.site
services:
  appserver:
    build_as_root:
      - a2enmod headers
      - a2enmod rewrite
      - service apache2 reload
    run_as_root:
      - "chown www-data: -R /app"
  database:
    portforward: 3318
    creds:
      user: lamp
      password: lamp
      database: lamp
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
  pma:
    type: phpmyadmin
    hosts: database  