name: wp-itec
recipe: wordpress
config:
  php: '7.4'
  webroot: .
  database: mysql
  xdebug: true
  ssl: true
proxy:
  appserver:
    - localhost
  database:
    - db.auto.lndo.site
  mailhog:
    - mail.auto.lndo.site
  pma:
    - pma.auto.lndo.site
  node:
    - node.auto.lndo.site
services:
  appserver:
    build_as_root:
      - a2enmod headers
      - a2enmod rewrite
      - service apache2 reload
    run_as_root:
      - "chown www-data: -R /app"
  database:
    type: mysql:5.7
    portforward: 3306
    creds:
      user: lamp
      password: lamp
      database: lamp
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026
  pma:
    type: phpmyadmin
    hosts: database
  node:
    type: node
    globals:
      npm: "latest"
      gulp-cli: "latest"
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
  gulp:
    service: node
  composer:
    service: appserver